version: '3'

services:
  hadoop-slave1:
    image: sench/hcd:1.0
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    networks: 
      - hadoop
    tty: true

  hadoop-slave2:
    image: sench/hcd:1.0
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    networks: 
      - hadoop
    tty: true
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    networks:
      - hadoop
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    tty: true

  hadoop-master:
    image: sench/hcd:1.0
    container_name: hadoop-master
    ports:
      - "50070:50070"
      - "8088:8088"
    hostname: hadoop-master
    links:
      - hadoop-slave1
      - hadoop-slave2
      - mysql
    networks:
      - hadoop
    tty: true

networks:
  hadoop: 
